
# Setting paramters
#PLY_SIZE=-DHAVERSMALL_DATASET
PLY_SIZE=-DHAVEREXTRALARGE_DATASET
#PLY_SIZE=-DLARGE_DATASET
PLY_MEASURE=-DPOLYBENCH_GFLOPS


# Generic stuff for all makefiles in polybench
CC=gcc
PLY_C_OPTIMIZE=-O3
PLY_OPTIONS=-DPOLYBENCH_USE_C99_PROTO -DPOLYFORD_VERBOSE


###            FOR PRINTING USE THE LINE BELOW


#PLY_OPTIONS=-DPOLYBENCH_DUMP_ARRAYS -DPOLYBENCH_USE_C99_PROTO -DPOLYFORD_VERBOSE


###            FOR PRINTING USE THE LINE ABOVE



PLY_C_EXTRA_FLAGS=-fopenmp
PLY_C_LDFLAGS=-lm # -lpapi  # C/C++ libraries go here
CFLAGS=${PLY_C_OPTIMIZE} ${PLY_OPTIONS} ${PLY_DATATYPE} ${PLY_SIZE} ${PLY_MEASURE} ${PLY_C_EXTRA_FLAGS}
LDFLAGS=${PLY_C_LDFLAGS}
# END generic stuff


# The making part
BENCHNAME=syr2k
EXTRA_FLAGS=

syr2k: syr2k.c syr2k.h
	${VERBOSE} ${CC} -o $(BENCHNAME) $(BENCHNAME).c ${CFLAGS} -I. -I./utilities ./utilities/polybench.c ${EXTRA_FLAGS} ${LDFLAGS}

clean:
	@ rm -f $(BENCHNAME)

